version: "3.7"

services:

  web-app:
    build: .

  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.3.0
    container_name: oauth2-proxy
    hostname: oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: sub
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://dev-l33337.okta.com/oauth2/default
      OAUTH2_PROXY_CLIENT_ID: api://default
      OAUTH2_PROXY_CLIENT_SECRET: NOT_USED_BUT_REQUIRED_VALUE
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: true
      OAUTH2_PROXY_SET_XAUTHREQUEST: true
      OAUTH2_PROXY_COOKIE_SECRET: NOT_USED_BUT_REQUIRED_VALUE_32b_
      
  nginx:
    image: nginx:1.21.6-alpine
    depends_on:
      - oauth2-proxy
    volumes:
      - ./nginx-default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
